# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSmokeTests():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_01HomeTitleLogoHeading(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    assert self.driver.title == "Teton Idaho CoC"
    elements = self.driver.find_elements(By.CSS_SELECTOR, "header .header-logo img[alt=\"Teton Chamber of Commerce Logo\"]")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, "header .header-title h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, "header .header-title h2").text == "Chamber of Commerce"
  
  def test_02HomeSpotlightsJoinUsLink(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1280, 800)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "header nav ul")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "header nav a[href=\"index.html\"]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "header nav a[href=\"join.html\"]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "header nav a[href=\"directory.html\"]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "header nav a[href=\"admin.html\"]")
    assert len(elements) > 0
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "section.main-spotlight")))
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//section[contains(@class,\'main-spotlight\')]/*[2]")))
    WebDriverWait(self.driver, 5).until(expected_conditions.invisibility_of_element_located((By.XPATH, "//section[contains(@class,\'main-spotlight\')]/*[3]")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "main.home-main section.main-hero a.a-button[href=\"join.html\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "main.home-main section.main-hero a.a-button[href=\"join.html\"]").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "input[name=\"fname\"]")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=\"fname\"]")
    assert len(elements) > 0
  
  def test_03DirectoryGridListTetonTurf(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
    self.driver.set_window_size(1280, 800)
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#directory-grid")))
    self.driver.find_element(By.CSS_SELECTOR, "#directory-grid").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#directory-data")))
    assert self.driver.find_element(By.CSS_SELECTOR, "div#directory-data section:last-child p").text == "Teton Turf and Tree"
    self.driver.find_element(By.CSS_SELECTOR, "#directory-list").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "div#directory-data section:last-child p").text == "Teton Turf and Tree"
  
  def test_04JoinWizardStep1ToStep2(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/join.html")
    self.driver.set_window_size(1280, 800)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=\"fname\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"fname\"]").clear()
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"fname\"]").send_keys("Isaac")
    value = self.driver.find_element(By.CSS_SELECTOR, "input[name=\"fname\"]").get_attribute("value")
    assert value == "Isaac"
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"lname\"]").clear()
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"lname\"]").send_keys("Smoke")
    value = self.driver.find_element(By.CSS_SELECTOR, "input[name=\"lname\"]").get_attribute("value")
    assert value == "Smoke"
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"bizname\"]").clear()
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"bizname\"]").send_keys("Smoke Test LLC")
    value = self.driver.find_element(By.CSS_SELECTOR, "input[name=\"bizname\"]").get_attribute("value")
    assert value == "Smoke Test LLC"
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"biztitle\"]").clear()
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"biztitle\"]").send_keys("QA")
    value = self.driver.find_element(By.CSS_SELECTOR, "input[name=\"biztitle\"]").get_attribute("value")
    assert value == "QA"
    self.driver.find_element(By.CSS_SELECTOR, "form[action=\"join-step2.html\"] input[type=\"submit\"][value=\"Next Step\"]").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "input[name=\"email\"]")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=\"email\"]")
    assert len(elements) > 0
  
  def test_05AdminInvalidLoginShowsError(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
    self.driver.set_window_size(1280, 800)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input#username")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "#username").clear()
    self.driver.find_element(By.CSS_SELECTOR, "#username").send_keys("wronguser")
    self.driver.find_element(By.CSS_SELECTOR, "#password").clear()
    self.driver.find_element(By.CSS_SELECTOR, "#password").send_keys("wrongpass")
    self.driver.find_element(By.CSS_SELECTOR, "input.mysubmit[value=\"Login\"]").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "span.errorMessage")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "span.errorMessage")
    assert len(elements) > 0
  
